openapi: 3.0.0
info:
  title: BrightWave Review Submission API
  version: 1.0.0
  description: API for managing customer reviews for products purchased on BrightWave's platform.

servers:
  - url: https://api.brightwave.com
    description: Production server
  - url: https://sandbox.api.brightwave.com
    description: Sandbox server for testing

paths:
  /reviews/submit:
    post:
      summary: Submit a review
      description: Allows verified purchasers to submit a review and star rating for a product.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
                - userId
                - rating
                - feedback
              properties:
                productId:
                  type: string
                  description: The unique identifier of the product being reviewed.
                userId:
                  type: string
                  description: The unique identifier of the user submitting the review.
                rating:
                  type: integer
                  description: Star rating for the product.
                  minimum: 1
                  maximum: 5
                feedback:
                  type: string
                  description: Text feedback provided by the user.
                  minLength: 10
                  maxLength: 1000
      responses:
        '200':
          description: Review submitted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Review submitted successfully."
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Validation failed: feedback contains profanity."
        '403':
          description: User is not a verified purchaser.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User is not verified to submit a review for this product."

  /reviews/validate-purchaser:
    get:
      summary: Validate purchaser
      description: Checks if the user is eligible to submit a review for a specific product.
      parameters:
        - name: productId
          in: query
          required: true
          schema:
            type: string
          description: The unique identifier of the product.
        - name: userId
          in: query
          required: true
          schema:
            type: string
          description: The unique identifier of the user.
      responses:
        '200':
          description: User is verified to submit a review.
          content:
            application/json:
              schema:
                type: object
                properties:
                  verified:
                    type: boolean
                    example: true
        '403':
          description: User is not a verified purchaser.
          content:
            application/json:
              schema:
                type: object
                properties:
                  verified:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "User has not purchased this product."

components:
  schemas:
    Review:
      type: object
      properties:
        productId:
          type: string
          description: The unique identifier of the product being reviewed.
        userId:
          type: string
          description: The unique identifier of the user submitting the review.
        rating:
          type: integer
          description: Star rating for the product.
          minimum: 1
          maximum: 5
        feedback:
          type: string
          description: Text feedback provided by the user.
